### ISSUE TITLE
Creating Time Entry Against no TP Entry

### ISSUE THREAD

**Issue by thyde1** [NewOrbit/twotime#14]
I am not able to record time against no TP entry.
If I enter no TP Id when prompted, I am allowed to continue.
However, upon entering "Yes" when asked if I am happy with my selection, I get:
`(node:21052) UnhandledPromiseRejectionWarning: TypeError: Cannot set property 'additionalNotes' of null
    at Object.<anonymous> (...\node_modules\twotime\bin\commands\start.js:54:49)
    at step (...\node_modules\twotime\bin\commands\start.js:32:23)
    at Object.next (...\node_modules\twotime\bin\commands\start.js:13:53)
    at fulfilled (...\node_modules\twotime\bin\commands\start.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:21052) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:21052) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

I would expect to either allow logging to no TP id, or to get a message saying that this is not supported (yet).

**Comment by Jameskmonger** [comment]
Fixed in 0.1.1 (c0fe25e79cc2ec3cf1bb664f777f19bb3e3dcdc4)
