### ISSUE TITLE
Should handle invalid/missing entities and reprompt

### ISSUE THREAD

**Issue by hisuwh** [NewOrbit/twotime#19]
When you enter an ID for which it cannot find the TP resource, it should handle this gracefully and reprompt you for a different ID.

Currently it errors and exits:

![image](https://user-images.githubusercontent.com/4470351/47374832-caeaae80-d6e6-11e8-8c08-9b1cceded7e2.png)

**Comment by hisuwh** [comment]
Sample output from onetime:
![image](https://user-images.githubusercontent.com/4470351/47375293-db4f5900-d6e7-11e8-95db-91f1666e549b.png)

**Comment by Jameskmonger** [comment]
Logged on TP https://neworbit.tpondemand.com/entity/42442-bug-reprompt-for-invalid-targetprocess-id

**Comment by Jameskmonger** [comment]
Released in 0.6.1 (9442526bd85459acc949d808d1af5acc1a2a9008)
