### ISSUE TITLE
Cannot press enter on projected time remaining

### ISSUE THREAD

**Issue by hisuwh** [NewOrbit/twotime#20]
- Do `twotime finish`
 - Shows projected time remaining
 - Press enter
 - Expect to submit time
 - Validation error: "enter a numeric value"

![image](https://user-images.githubusercontent.com/4470351/47376044-93313600-d6e9-11e8-8ce6-3ae04ab9a407.png)

**Comment by Jameskmonger** [comment]
This is by design unfortunately, new requirement is that you manually need to enter the time remaining rather than it defaulting to the projected one

The error message can be clarified though

**Comment by hisuwh** [comment]
😢 
Perhaps something like "Please enter time remaning"

**Comment by Jameskmonger** [comment]
Released in 0.5.1 (fbced5c0ee4c6fe971d0f7bc6dae3837e9eb8827)
