### ISSUE TITLE
Show version on help or implement -v

### ISSUE THREAD

**Issue by hisuwh** [NewOrbit/twotime#22]
Help screen should show version, or there should be a -v option so that you can check you are running the latest version:

![image](https://user-images.githubusercontent.com/4470351/47419851-fddb8380-d774-11e8-8a34-8e9dd9c677b7.png)

**Comment by Jameskmonger** [comment]
This will be done automatically if we call `commander.version` - normally people import `package.json` and parse from that

**Comment by Jameskmonger** [comment]
Released in 0.4.0 (2724342a4f30faa00ce62334dc601bfe49376380)
