### ISSUE TITLE
Starts timer even if "Are you happy with your selection" is No

### ISSUE THREAD

**Issue by davidgruar** [NewOrbit/twotime#29]
- `twotime start`
- Answer "No" to "Are you happy with your selection?"
- Timer is still started

It would be nice if answering "No" allowed you to go back and edit the field you got wrong, but I guess that's OOS.

**Comment by Jameskmonger** [comment]
Logged on TP as https://neworbit.tpondemand.com/entity/42472-bug-saying-no-to-confirmation-still

**Comment by Jameskmonger** [comment]
Fixed in 0.6.2 (0b873670a21cd5051fb4e06f8a4832f527080db1)
