### ISSUE TITLE
Notes are not added to a timer with no associated TP id

### ISSUE THREAD

**Issue by thyde1** [NewOrbit/twotime#36]
v0.9.2

![image](https://user-images.githubusercontent.com/16574024/47644658-ac613900-db66-11e8-89f0-5e55ff2e9baf.png)

![image](https://user-images.githubusercontent.com/16574024/47644677-b6833780-db66-11e8-95cf-d8cbe256bb7f.png)

**Comment by Jameskmonger** [comment]
Fixed in 0.9.3 (1428261eaf016792024c36283008b29fc565ca2e)
