### ISSUE TITLE
resume throws

### ISSUE THREAD

**Issue by thyde1** [NewOrbit/twotime#37]
v0.9.2

twotime resume fails.

I had unfinished timers with no notes, and with no associated TP ids.

![image](https://user-images.githubusercontent.com/16574024/47644790-0b26b280-db67-11e8-9171-0f77cbcd0b91.png)

**Comment by Jameskmonger** [comment]
Fixed in 0.9.4 (2f19405d17d942402f19febf691104bf801f1c26)
