### ISSUE TITLE
Can't resume timers without a tp ids

### ISSUE THREAD

**Issue by ksstott** [NewOrbit/twotime#41]
version 0.9.6

Timers without a tp id associated cannot be resumed with `twotime resume`

![image](https://user-images.githubusercontent.com/3505022/47710570-0297b000-dc2b-11e8-90bf-3f606f4d1508.png)

![image](https://user-images.githubusercontent.com/3505022/47710592-0e837200-dc2b-11e8-9219-e869996d0775.png)

**Comment by Jameskmonger** [comment]
👍 

I found this this morning, logged on TP as https://neworbit.tpondemand.com/entity/42526-bug-resume-uses-isrunningorunfinished-filter

Fix incoming ASAP

**Comment by Jameskmonger** [comment]
Fixed in 0.9.7 (921f556f431cd5d5fbd5fccda5806732923cbd50)
