### ISSUE TITLE
Better error handling - not just displaying the same message when something goes wrong.

### ISSUE THREAD

**Issue by BaronBeans** [NewOrbit/twotime#63]
`(node:12092) UnhandledPromiseRejectionWarning: #<Object>
(node:12092) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12092) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by petevb** [comment]
Resolved by #70, I believe.
